### ISSUE TITLE
deprecate roadmap (for now)

### ISSUE THREAD

**Issue by technobaboo** [StardustXR/website#13]
remove all links to roadmap and warn at top of page that it's outdated

**Comment by Holgermueller** [comment]
Hi, my name is Holger, and I'm looking to contribute to some open source projects. This looks like something I could tackle. I was wondering if it is still up for grabs.

**Comment by technobaboo** [comment]
yeah sure, go for it!

**Comment by Holgermueller** [comment]
Awesome, thank you!
Before I get going, and so I make sure I understand what needs to be done, do you want the code for the links deleted or just commented out?

**Comment by technobaboo** [comment]
oops didn't see this, you can delete it since we have git history

**Comment by Holgermueller** [comment]
OK, cool.  I'll get on this as soon as I can.

**Comment by technobaboo** [comment]
forgot to close it despite it being done!
